raw_data_path: './data/raw/ASRS_all_factors_raw.xlsx'
output_path: './data/processed/ASRS_all_factors_extracted.csv'

Level_1:
  Errors:
  - Anomaly:Conflict Airborne Conflict
  - Anomaly:Conflict Ground Conflict, Critical
  - Anomaly:Conflict Ground Conflict, Less Severe
  - Anomaly:Conflict NMAC
  - Anomaly:Deviation - Altitude Excursion From Assigned Altitude
  - Anomaly:Deviation - Altitude Overshoot
  - Anomaly:Deviation - Altitude Undershoot
  - Anomaly:Deviation - Speed All Types
  - Anomaly:Deviation - Track / Heading All Types
  - Anomaly:Inflight Event / Encounter Loss Of Aircraft Control
  - Anomaly:Ground Event / Encounter Loss Of Aircraft Control
  - Anomaly:Inflight Event / Encounter Unstabilized Approach
  - Anomaly:Inflight Event / Encounter VFR In IMC
  - Anomaly:Inflight Event / Encounter CFTT / CFIT
  - Anomaly:Inflight Event / Encounter Fly Away (UAS)
  - Anomaly:Inflight Event / Encounter Fuel Issue
  - Anomaly:Ground Event / Encounter Fuel Issue
  - Anomaly:Ground Event / Encounter Gear Up Landing

  Violations:
  - Anomaly:Airspace Violation All Types
  - Anomaly:Deviation / Discrepancy - Procedural Clearance
  - Anomaly:Deviation / Discrepancy - Procedural FAR
  - Anomaly:Deviation / Discrepancy - Procedural Hazardous Material Violation
  - Anomaly:Deviation / Discrepancy - Procedural Landing Without Clearance
  - Anomaly:Deviation / Discrepancy - Procedural MEL / CDL
  - Anomaly:Deviation / Discrepancy - Procedural Other / Unknown
  - Anomaly:Deviation / Discrepancy - Procedural Published Material / Policy
  - Anomaly:Deviation / Discrepancy - Procedural Unauthorized Flight Operations (UAS)
  - Anomaly:Deviation / Discrepancy - Procedural Weight And Balance
  - Anomaly:Flight Deck / Cabin / Aircraft Event Passenger Misconduct
  - Anomaly:Flight Deck / Cabin / Aircraft Event Passenger Electronic Device

Level_2:
  Situational_Factors:
  # - Contributing Factors:Weather
  # - Contributing Factors:Environment - Non Weather Related
  - Anomaly:Ground Event / Encounter Weather / Turbulence
  - Anomaly:Inflight Event / Encounter Weather / Turbulence
  - Anomaly:Inflight Event / Encounter Wake Vortex Encounter
  - Anomaly:Inflight Event / Encounter Bird / Animal
  - Anomaly:Ground Event / Encounter Person / Animal / Bird
  - Anomaly:Ground Event / Encounter FOD
  - Anomaly:Ground Event / Encounter Object
  - Anomaly:Inflight Event / Encounter Object
  - Anomaly:Ground Event / Encounter Jet Blast
  - Anomaly:Ground Excursion Ramp/Runway/Taxiway
  - Anomaly:Ground Incursion Ramp/Runway/Taxiway
  - Anomaly:ATC Issue All Types
  - Anomaly:Aircraft Equipment Problem Critical
  - Anomaly:Aircraft Equipment Problem Less Severe
  - Anomaly:Ground Event / Encounter Ground Equipment Issue
  # - Contributing Factors:ATC Equipment / Nav Facility / Buildings
  # - Contributing Factors:Equipment / Tooling
  # - Contributing Factors:Software and Automation

  Personnel_Factors:
  - Human Factors:Communication Breakdown
  - Human Factors:Troubleshooting
  - Human Factors:Training / Qualification
  - Human Factors:Human-Machine Interface

  Condition_of_Operators:
  - Human Factors:Confusion
  - Human Factors:Distraction
  - Human Factors:Situational Awareness
  - Human Factors:Time Pressure
  - Human Factors:Workload
  - Human Factors:Other / Unknown
  - Human Factors:Fatigue
  - Human Factors:Physiological - Other

Level_3:
  Inadequate_Supervision:
  - Contributing Factors:Staffing
  - Contributing Factors:Manuals
  - Human Factors:Training / Qualification

  Failure_to_Correct_Known_Problems:
  - Contributing Factors:MEL
  - Contributing Factors:Procedure

  Planned_Inappropriate_Operations: []
  Supervisory_Violations: []

Level_4:

  Organizational_Process:
  - Contributing Factors:Chart Or Publication
  - Contributing Factors:Logbook Entry
  - Contributing Factors:Procedure
  - Contributing Factors:Manuals
  - Contributing Factors:MEL

  Organizational_Climate:
  - Contributing Factors:Company Policy
  - Contributing Factors:Human Factors

  Resource_Management:
  - Contributing Factors:Incorrect / Not Installed / Unavailable Part
  - Contributing Factors:Software and Automation
  - Contributing Factors:Aircraft
  - Contributing Factors:Airport
  - Contributing Factors:Airspace Structure
  - Contributing Factors:ATC Equipment / Nav Facility / Buildings
  - Contributing Factors:Equipment / Tooling
  - Contributing Factors:Staffing
